apiVersion: v1
appVersion: 0.4.8
description: wave chart that runs on kubernetes
home: https://github.com/pusher/wave
keywords:
- wave
- kubernetes
name: pusher-wave
sources:
- https://github.com/pusher/wave
version: 0.4.8
